name: CI

on:
  push:
    branches: [ "master" ]
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - name: Cache Maven packages
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven

      - name: Download and install TextAPI locally
        run: |
          curl -L https://github.com/thenolle/textapi/releases/download/v1.0.6/textapi-1.0.6.jar \
            -o textapi.jar
          mvn install:install-file \
            -Dfile=textapi.jar \
            -DgroupId=com.nolly.mc \
            -DartifactId=textapi \
            -Dversion=1.0.6 \
            -Dpackaging=jar

      - name: Build with Maven
        run: mvn -B clean package

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: PackItems
          path: target/*.jar
